[package]
edition = "2021"
name = "axum-nip98"
version = "0.1.0"

[dependencies]
axum = { version = "0.6.20", features = ["tokio"] }
nostr-web = { path = "../../" }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
